-- FUNCIÓN PARA VALIDAR EL RUT
CREATE OR REPLACE FUNCTION VALIDAR_RUT() RETURNS TRIGGER AS $$
DECLARE
    STRLEN INT; -- LONGITUD DEL RUT
    I INT := 1; -- CONTADOR PARA RECORRER CADA CARACTER
    J INT := 2; -- PESO INICIAL PARA EL CÁLCULO DEL DV
    SUMA NUMERIC := 0; -- VARIABLE PARA ALMACENAR LA SUMA DEL CÁLCULO
    TEMPRUT VARCHAR(12); -- RUT INVERSO PARA CÁLCULO
    VERIFY_DV VARCHAR(2); -- DÍGITO VERIFICADOR CALCULADO
BEGIN
    STRLEN := LENGTH(NEW.RUT::TEXT); -- OBTENER LA LONGITUD DEL RUT

    IF STRLEN = 8 OR STRLEN = 7 THEN -- VERIFICAR LONGITUD VÁLIDA
        TEMPRUT := REVERSE(NEW.RUT::TEXT); -- INVERTIR EL RUT

        WHILE I <= STRLEN LOOP -- RECORRER CADA CARACTER DEL RUT
            SUMA := SUMA + (CAST(SUBSTRING(TEMPRUT, I, 1) AS INTEGER) * J); 
            I := I + 1;

            IF J = 7 THEN
                J := 2; -- REINICIAR PESO A 2
            ELSE
                J := J + 1; -- INCREMENTAR PESO
            END IF;
        END LOOP;

        VERIFY_DV := 11 - (SUMA % 11); -- CÁLCULO DEL DÍGITO VERIFICADOR

        -- AJUSTAR EL DÍGITO VERIFICADOR CALCULADO
        IF VERIFY_DV = '11' THEN
            VERIFY_DV := '0'; -- SI ES 11, SE CONVIERTE A 0
        ELSIF VERIFY_DV = '10' THEN
            VERIFY_DV := 'K'; -- SI ES 10, SE CONVIERTE A K
        ELSE
            VERIFY_DV := VERIFY_DV::VARCHAR; -- CONVERTIR A VARCHAR
        END IF;

        -- COMPARAR EL DV CALCULADO CON EL DV PROPORCIONADO
        IF LOWER(NEW.DIGITOVERIFICADOR) = VERIFY_DV THEN
            RETURN NEW; -- DEVOLVER EL REGISTRO SI SON IGUALES
        ELSE
            RAISE EXCEPTION 'DÍGITO VERIFICADOR NO VÁLIDO'; -- ERROR EN CASO DE DISCREPANCIAS
        END IF;
    END IF;

    -- RETORNAR EXCEPCIÓN SI LA LONGITUD DEL RUT NO ES VÁLIDA
    RAISE EXCEPTION 'RUT INGRESADO NO VÁLIDO';
END;
$$ LANGUAGE PLPGSQL;

-- TRIGGER PARA VALIDAR RUT EN MEDICOS
CREATE OR REPLACE TRIGGER TG_VALIDARRUTMEDICO BEFORE INSERT ON MEDICOS FOR EACH ROW EXECUTE FUNCTION VALIDAR_RUT();

-- TRIGGER PARA VALIDAR RUT EN PACIENTE
CREATE OR REPLACE TRIGGER TG_VALIDARRUTPACIENTE BEFORE INSERT ON PACIENTE FOR EACH ROW EXECUTE FUNCTION VALIDAR_RUT();

-- TRIGGER PARA VALIDAR RUT EN SUPERVISOR
CREATE OR REPLACE TRIGGER TG_VALIDARRUTSUPERVISOR BEFORE INSERT ON SUPERVISOR FOR EACH ROW EXECUTE FUNCTION VALIDAR_RUT();
